### ISSUE TITLE
Need help with Angular integration 

### ISSUE THREAD

**Issue by skota-in** [timotejroiko/sweph#10]
I'm building an Angular application but unable to integrate sweph library.

Error:
`./node_modules/sweph/index.mjs:1:0-39 - Error: Module not found: 
Error: Can't resolve 'module' in 'C:\Users\admin\Workspace\github\sweph\sweph-ui\node_modules\sweph'` 

Here is the [Git repo](https://github.com/skota-in/sweph)

It has 2 projects. (both are NodeJS frameworks)

sweph-ui = Angular application
sweph-api = NestJS application

NestJS, its working fine.

So want to know if there is a workaround for sweph + angular.

**Comment by timotejroiko** [comment]
hello, unfortunately sweph does not support running on browsers, it is a NodeJS-only library.

It works on the NestJS side because its executed on the server side, in a NodeJS server, but the Angular application is bundled and sent to run on the browser, where it cannot run.

The solution is to have sweph only on the server side, and create an api to interact with it from the Angular side through fetch requests or similar methods.

**Comment by skota-in** [comment]
Thanks for the reply. You covered that in [Limitations](https://github.com/timotejroiko/sweph#limitations)

But looking at the error, i felt like tweaking tsconfig will help Angular to load the module.

Will give a try with [emscripten](https://emscripten.org/) & WebAssembly
